import React from "react";
import "../Styles/Work/work.css"

function Work() {

    return (
        <div className="Work__container" id="Work">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore dolorem officiis tenetur error, et dolore adipisci quaerat minima ea magni soluta nemo dolor beatae excepturi temporibus assumenda dolorum nam obcaecati?Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore dolorem officiis tenetur error, et dolore adipisci quaerat minima ea magni soluta nemo dolor beatae excepturi temporibus assumenda dolorum nam obcaecati?Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore dolorem officiis tenetur error, et dolore adipisci quaerat minima ea magni soluta nemo dolor beatae excepturi temporibus assumenda dolorum nam obcaecati?Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore dolorem officiis tenetur error, et dolore adipisci quaerat minima ea magni soluta nemo dolor beatae excepturi temporibus assumenda dolorum nam obcaecati?Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore dolorem officiis tenetur error, et dolore adipisci quaerat minima ea magni soluta nemo dolor beatae excepturi temporibus assumenda dolorum nam obcaecati?Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore dolorem officiis tenetur error, et dolore adipisci quaerat minima ea magni soluta nemo dolor beatae excepturi temporibus assumenda dolorum nam obcaecati?Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore dolorem officiis tenetur error, et dolore adipisci quaerat minima ea magni soluta nemo dolor beatae excepturi temporibus assumenda dolorum nam obcaecati?Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore dolorem officiis tenetur error, et dolore adipisci quaerat minima ea magni soluta nemo dolor beatae excepturi temporibus assumenda dolorum nam obcaecati?Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore dolorem officiis tenetur error, et dolore adipisci quaerat minima ea magni soluta nemo dolor beatae excepturi temporibus assumenda dolorum nam obcaecati?Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore dolorem officiis tenetur error, et dolore adipisci quaerat minima ea magni soluta nemo dolor beatae excepturi temporibus assumenda dolorum nam obcaecati?Lorem ipsum dolor sit amet consectetur adipisicing elit
        </div>
    )
}

export default Work;